server:
  port: 7454
spring:
  jpa:
    hibernate: org.hibernate.dialect.MySQLDialect
    ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    #    liquibase:
    #      change-log: classpath:liquibase/db/changelog/db.changelog-master.yaml
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:mysql://localhost:3306/tutor_app
    #     passwords to DB
    password: sapereaude8
#    password: sapereaude8